# Generated by Django 3.2.4 on 2021-06-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleExposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_asignado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo_validacion', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('mail', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateField()),
                ('horaVenta', models.DateField()),
                ('monto', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('tarifa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_fin', models.DateField()),
                ('fecha_fin_replanificada', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_inicio_replanificada', models.DateField()),
                ('hora_apertura', models.DateField()),
                ('hora_cierre', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('codigoSensor', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('duracionExtendida', models.DateField()),
                ('duracionResumida', models.DateField()),
                ('fechaCreacion', models.DateField()),
                ('fechaPrimerIngreso', models.DateField()),
                ('nombreObra', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('valuacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadAlumnos', models.IntegerField()),
                ('cantidadAlumnosConfirmada', models.IntegerField()),
                ('duracionEstimada', models.DateField()),
                ('fechaHoraCreacion', models.DateField()),
                ('fechaHoraReserva', models.DateField()),
                ('horaFinReal', models.DateField()),
                ('horaInicioReal', models.DateField()),
                ('numeroReserva', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantMaximaVisitantes', models.IntegerField()),
                ('cantMaxPorGuia', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tarifa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('hora_fin', models.DateField()),
                ('hora_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFinVigencia', models.DateField()),
                ('monto', models.IntegerField()),
                ('montoAdicionalGuia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('caducidad', models.DateField()),
            ],
        ),
    ]
