# Generated by Django 3.2.4 on 2021-06-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_detalleexposicion_empleado_entrada_exposicion_obra_reservavisita_sede_sesion_tarifa_tipoentrada_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='tarifa',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='tarifa',
        ),
    ]
