# Generated by Django 3.2.4 on 2021-06-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20210621_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.usuario'),
        ),
    ]
