# Generated by Django 3.2.4 on 2021-06-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_sesion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado'),
        ),
    ]
