# Generated by Django 3.2.4 on 2021-06-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_empleado_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='exposicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.exposicion'),
        ),
        migrations.AddField(
            model_name='sede',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.tarifa'),
        ),
    ]
