# Generated by Django 3.2.4 on 2021-06-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20210621_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='tipoEntrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.tipoentrada'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='tipoVisita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.tipovisita'),
        ),
    ]
