# Generated by Django 3.2.4 on 2021-06-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20210621_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.sede'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.tarifa'),
        ),
    ]
