# Generated by Django 3.2.4 on 2021-06-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_exposicion_detalles_exposicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleexposicion',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.obra'),
        ),
    ]
