# Generated by Django 3.2.4 on 2021-06-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_detalleexposicion_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sede',
        ),
        migrations.AddField(
            model_name='sede',
            name='empleado_creo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.empleado'),
        ),
    ]
